### ISSUE TITLE
livereload support

### ISSUE THREAD

**Issue by indusninja** [BretFisher/jekyll-serve#14]
I'm not getting live reloading support in the `jekyll-serve` image. Is that missing or is there a way I can pass the `--livereload` argument from docker-compose file?

I'm talking about the `jekyll serve --livereload` command that was introduced in [Jekyll 3.7.0](https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/)

**Comment by BretFisher** [comment]
You can override the Dockerfile CMD with a docker-compose.yml `command:` or just fork this repo and create your own image with the settings you prefer :)

**Comment by indusninja** [comment]
This version of the docker-compose file works for me. Thank you for the help 👍 

```
version: '2'

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '8085:4000'
    command: bundle exec jekyll s --livereload
```
